# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    routing_loader: false
    body_listener: true
    body_converter:
      enabled: true
      validate: true
      validation_errors_argument: violations
    serializer:
      serialize_null: true
    view:
        view_response_listener:  true
        formats: { json: true, xml: false, rss: false }
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: '^/', stop: true }
    exception:
        exception_controller: 'fos_rest.exception.controller:showAction'
        codes:
            Doctrine\ORM\EntityNotFoundException: 404
            App\Exception\ResourceValidationException: 400
            App\Exception\ForbiddenException: 403
        messages:
            Doctrine\ORM\EntityNotFoundException: true
            App\Exception\ResourceValidationException: true
            App\Exception\ForbiddenException: true
